# Stage 1: Build
FROM node:20-alpine AS builder
WORKDIR /app

# Copy all local packages and website source
COPY packages/ ./packages/
COPY apps/website/package.json apps/website/tsconfig.json apps/website/next.config.mjs ./website/

# =============================================================================
# CRITICAL: npm v10+ with file: dependencies creates symlinks but does NOT walk
# the linked package's dependency tree. @davincios/next, @davincios/db-postgres,
# @davincios/cms, and @davincios/richtext-lexical all have transitive npm deps
# (drizzle-orm, pino, pg, @dnd-kit/core, graphql, lexical, etc.) that must be
# explicitly installed.
#
# Strategy:
#   1. npm install - installs website base deps (next, react, etc.) + creates
#      file: symlinks for @davincios packages
#   2. npm install --no-save - installs ALL transitive deps explicitly
#   3. Replace symlinks with direct copies + create stubs for missing packages
# =============================================================================
RUN cd website && \
    echo "=== Step 1: Install website base dependencies ===" && \
    npm install && \
    echo "" && \
    echo "=== Step 2: Install ALL transitive dependencies from @davincios packages ===" && \
    echo "  (npm v10+ does NOT walk file: linked package dependency trees)" && \
    npm install --no-save \
      @dnd-kit/core@6.3.1 \
      @dnd-kit/modifiers@9.0.0 \
      @dnd-kit/sortable@10.0.0 \
      @faceless-ui/modal@3.0.0 \
      @faceless-ui/scroll-info@2.0.0 \
      @lexical/clipboard@0.41.0 \
      @lexical/headless@0.41.0 \
      @lexical/html@0.41.0 \
      @lexical/link@0.41.0 \
      @lexical/list@0.41.0 \
      @lexical/mark@0.41.0 \
      @lexical/react@0.41.0 \
      @lexical/rich-text@0.41.0 \
      @lexical/selection@0.41.0 \
      @lexical/table@0.41.0 \
      @lexical/utils@0.41.0 \
      @next/env@^15.1.5 \
      @types/busboy@1.5.4 \
      @types/pg@8.20.0 \
      acorn@8.16.0 \
      ajv@8.18.0 \
      bson-objectid@2.0.4 \
      busboy@^1.6.0 \
      ci-info@^4.1.0 \
      console-table-printer@2.12.1 \
      croner@10.0.1 \
      csstype@3.1.3 \
      dataloader@2.2.3 \
      deepmerge@4.3.1 \
      dequal@2.0.3 \
      drizzle-kit@0.31.7 \
      drizzle-orm@0.45.2 \
      escape-html@1.0.3 \
      file-type@21.3.4 \
      get-tsconfig@4.8.1 \
      graphql@^16.8.1 \
      graphql-http@^1.22.0 \
      graphql-playground-html@1.6.30 \
      http-status@2.1.0 \
      image-size@2.0.2 \
      ipaddr.js@2.2.0 \
      jose@5.10.0 \
      json-schema-to-typescript@15.0.3 \
      jsox@1.2.121 \
      lexical@0.41.0 \
      mdast-util-from-markdown@2.0.2 \
      mdast-util-mdx-jsx@3.1.3 \
      micromark-extension-mdx-jsx@3.0.1 \
      minimist@1.2.8 \
      path-to-regexp@6.3.0 \
      pg@8.20.0 \
      pino@9.14.0 \
      pino-pretty@13.1.2 \
      pluralize@8.0.0 \
      prompts@2.4.2 \
      qs-esm@8.0.1 \
      range-parser@1.2.1 \
      react-error-boundary@4.1.2 \
      sanitize-filename@1.6.3 \
      sass@1.77.4 \
      to-snake-case@1.0.0 \
      ts-essentials@10.0.3 \
      tsx@4.22.4 \
      undici@7.24.4 \
      uuid@13.0.2 \
      ws@^8.16.0 && \
    echo "" && \
    echo "=== Step 3: Replace npm symlinks with direct copies for file: dependencies ===" && \
    rm -rf node_modules/@davincios && \
    mkdir -p node_modules/@davincios && \
    cp -r ../packages/davincios node_modules/@davincios/cms && \
    cp -r ../packages/next node_modules/@davincios/next && \
    cp -r ../packages/db-postgres node_modules/@davincios/db-postgres && \
    cp -r ../packages/richtext-lexical node_modules/@davincios/richtext-lexical && \
=======
    echo "  Replaced @davincios/cms, next, db-postgres, richtext-lexical" && \
    echo "" && \
    echo "=== Step 4: Create stub packages for missing @davincios/* dependencies ===" && \
    mkdir -p node_modules/@davincios/drizzle node_modules/@davincios/graphql node_modules/@davincios/ui node_modules/@davincios/translations && \
    echo "  Created stub directories" && \
    echo '{"name":"@davincios/drizzle","version":"3.85.1","main":"./index.js","type":"module","exports":{"./postgres":"./postgres.js","./package.json":"./package.json",".":"./index.js"}}' > node_modules/@davincios/drizzle/package.json && \
    echo "  (drizzle stubs will be generated by create-drizzle-stub.js after scripts/ is copied)" && \
    echo '{"name":"@davincios/graphql","version":"3.85.1","main":"./index.js","type":"module","exports":{"./package.json":"./package.json",".":"./index.js"}}' > node_modules/@davincios/graphql/package.json && \
    echo "export * from 'graphql'; export { default as graphqlHTTP } from 'graphql-http';" > node_modules/@davincios/graphql/index.js && \
    echo "  Created @davincios/graphql (re-exports graphql)" && \
    echo "  (@davincios/translations stubs will be generated by create-translations-stub.js after scripts/ is copied)" && \
    echo '{"name":"@davincios/translations","version":"3.85.1","main":"./index.js","type":"module","exports":{"./package.json":"./package.json",".":"./index.js","./utilities":"./utilities.js","./languages/*":"./languages/*.js"}}' > node_modules/@davincios/translations/package.json && \
    echo "  Created @davincios/translations package.json" && \
    echo '{"name":"@davincios/ui","version":"3.85.1","main":"index.js","exports":{".":"./index.js","./package.json":"./package.json","./utilities/getClientConfig":"./utilities/getClientConfig.js","./elements/Banner":"./elements/Banner.js","./elements/RenderServerComponent":"./elements/RenderServerComponent.js","./rsc":"./rsc.js","./utilities/buildFormState":"./utilities/buildFormState.js","./utilities/buildTableState":"./utilities/buildTableState.js","./utilities/getClientSchemaMap":"./utilities/getClientSchemaMap.js","./utilities/getFolderResultsComponentAndData":"./utilities/getFolderResultsComponentAndData.js","./utilities/getSchemaMap":"./utilities/getSchemaMap.js","./utilities/schedulePublishHandler":"./utilities/schedulePublishHandler.js","./assets":"./assets.js","./shared":"./shared.js","./forms/fieldSchemasToFormState":"./forms/fieldSchemasToFormState.js","./utilities/buildFieldSchemaMap/traverseFields":"./utilities/buildFieldSchemaMap/traverseFields.js"}}' > node_modules/@davincios/ui/package.json && \
    mkdir -p node_modules/@davincios/ui/utilities node_modules/@davincios/ui/elements node_modules/@davincios/ui/forms node_modules/@davincios/ui/utilities/buildFieldSchemaMap && \
    echo "  Created stub directory structure" && \
    echo "" && \
    echo "=== Step 5: Create alias symlink for bare 'davincios' -> @davincios/cms ===" && \
    ln -s @davincios/cms node_modules/davincios && \
    echo "  Created symlink: davincios -> @davincios/cms"

# Copy scripts
COPY scripts/ ./scripts/

# Run stub generators
RUN cd website && node ../scripts/create-ui-stub.js
RUN cd website && node ../scripts/create-drizzle-stub.js
RUN cd website && node ../scripts/create-translations-stub.js

>>>>>>> eada38a4dfc6b6a73130f42c42eb11bc8e767428
# The pre-built dist/ files in @davincios packages may still contain
# Legacy upstream function names, imports, and file names are normalized to DaVinciOS.
COPY scripts/strip-legacy-brand.mjs ./scripts/strip-legacy-brand.mjs
RUN node ./scripts/strip-legacy-brand.mjs

# Accept NEXT_PUBLIC_SITE_URL at build time for correct og:image URLs
ARG NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL

COPY apps/website/src/ ./website/src/
COPY apps/website/public/ ./website/public/
RUN cd website && npm run build

# Stage 2: Production
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV DAVINCIOS_CONFIG_PATH=./src/daVinciOS.config.ts

COPY --from=builder /app/website/.next/standalone ./
COPY --from=builder /app/website/.next/static ./.next/static
COPY --from=builder /app/website/public ./public

# Copy DaVinciOS config file and source so it's findable at runtime
COPY --from=builder /app/website/src ./src

# Copy ALL node_modules from builder — ensures all transitive dependencies
# (e.g. @next/env, drizzle-orm, pino, pg, etc.) are available at runtime.
# Selective copies caused ERR_MODULE_NOT_FOUND for packages like @next/env/dist/index.js
# which the DaVinciOS runtime loader requires.
COPY --from=builder /app/website/node_modules ./node_modules

EXPOSE 3000

CMD ["node", "server.js"]
